version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'maven'
    directories:
      - '**/*'
    schedule:
      interval: 'weekly'
