services:
  spring-boot-quartz-cluster-example-mysql:
    container_name: spring-boot-quartz-cluster-example-mysql
    image: mysql:9.2.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=12345
    logging:
      driver: json-file
      options:
        max-size: "250m"
        max-file: "10"
