version: '3.7'
services:
  mysql:
    image: mysql:5.7.22
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=12345
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"
